### ISSUE TITLE
line 89 sentence fragment

### ISSUE THREAD

**Issue by sarahhammarlund** [briandconnelly/nicheconstruct#81]
I think the sentence "Whereas under negative niche construction, selection favors a type other than the constructor, which creates an opportunity for novel adaptation." is technically not a complete sentence, because of "whereas."  An alternate is to start the sentence with, "In contrast, under negative niche construction..."  Or we could link it to the previous sentence, but that creates quite a long sentence.

**Comment by briandconnelly** [comment]
Yeah, based on some of the comments, Ben and I thought we should make sentences like this (and what you reference in #82) more explicit. We'll need to talk about how niche construction affects RELATIVE fitness, how the effect of niche construction is density dependent (in response to reviewer 2's comment about line 261), and possibly elsewhere.

Around line 261 is probably a great place to go over all of the details, since the invasion stuff in the following subsections are directly affected by the specifics of the niche construction.
