### ISSUE TITLE
Are Sissy Hankshaw's thumbs ever described as a hindrance?

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/nicheconstruct#83]
Ben and I talked (mostly jokingly) about starting a book club to actually read the novel, but for both projects, we should find some specific mention that Sissy's thumbs were a hindrance in some way.

**Comment by KatieDickinson** [comment]
Sarah has the book! And I looked at 1/2 Price Books the other day (by Trader Joe's on Roosevelt) because I was going to buy you and Ben a copy and they have several copies for ~$3. I should have bought them but I was in the middle of moving so I didn't want to get them at that moment.
But I believe they were a hindrance (for example she could not do buttons so it was hard to get dressed)...

**Comment by sarahhammarlund** [comment]
Hehe I bought it and have made it through about two pages... Wasn't she teased as a child for her weird-looking thumbs?

**Comment by KatieDickinson** [comment]
Limited career options (could not be a surgeon or mechanic for example comments by her dad and uncle, pg 11)
Due to impaired dexterity life act ivies and careers would be limited (doctor, pg 20)
In school she couldn't do typing, or Home-Ec (couldn't sew) or art (pg 34)

**Comment by sarahhammarlund** [comment]
Another Sissy question:

Review 1 said, "L69 Personally I find the Tom Robbins analogy a bit of a stretch and while I know the literature in question many will not so it's kind of unclear what's added here; it's also potentially confusing - Sissy's thumbs help her hitchhike as much as anyone else, so it's not clearly paying a cost to help others."

We've already found great examples of the cost (thanks Katie!) but about Sissy's thumbs being able to help others hitchhike too... Does that happen often in the book?
